---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplenodeapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: samplenodeapp-operator
  template:
    metadata:
      labels:
        name: samplenodeapp-operator
    spec:
      serviceAccountName: samplenodeapp-operator
      containers:
        - name: samplenodeapp-operator
          # Replace this with the built image name
          image: "quay.io/gunjangarge/sample-node-app-operator:v1"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "samplenodeapp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
      volumes:
        - name: runner
          emptyDir: {}
