apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samplenodeapps.samplenodeapp.exampleoperator.com
spec:
  group: samplenodeapp.exampleoperator.com
  version: v1alpha1
  names:
    kind: SampleNodeApp
    listKind: SampleNodeAppList
    plural: samplenodeapps
    singular: samplenodeapp
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
