---
# tasks file for samplenodeapp
- name: create prd application
  community.kubernetes.k8s:
   definition: "{{ lookup('template', item) | from_yaml  }}"
  with_items:
  - deploy.yaml.j2
  - service.yaml.j2
  - route.yaml.j2
